#!/usr/bin/env node
/**
 * Export current Supabase schema to migration file
 * Usage: node scripts/export-schema.mjs
 *
 * This script:
 * 1. Connects to Supabase using SUPABASE_SERVICE_ROLE_KEY
 * 2. Extracts all tables, functions, policies, triggers
 * 3. Generates a comprehensive migration file
 * 4. Saves to supabase/migrations/NNNN_schema-snapshot.sql
 */

import { createClient } from '@supabase/supabase-js';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve } from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error('❌ Missing environment variables:');
  console.error('   NEXT_PUBLIC_SUPABASE_URL=' + (SUPABASE_URL ? '✓' : '✗'));
  console.error('   SUPABASE_SERVICE_ROLE_KEY=' + (SERVICE_ROLE_KEY ? '✓' : '✗'));
  console.error('\n📝 Add these to .env.local');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});

async function getSchema() {
  console.log('\n📡 Connecting to Supabase...');
  console.log(`   URL: ${SUPABASE_URL}`);

  const { data: tables, error: tablesError } = await supabase
    .rpc('get_table_definitions') // Custom RPC if available, fallback to manual query
    .catch(async () => {
      // Fallback: Use information_schema
      console.log('   Using information_schema (no custom RPC)');
      return supabase.rpc('exec', {
        sql: `
          SELECT table_name, column_name, data_type, is_nullable, column_default
          FROM information_schema.columns
          WHERE table_schema = 'public'
          ORDER BY table_name, ordinal_position
        `,
      });
    });

  if (tablesError) {
    console.error('❌ Error fetching tables:', tablesError.message);
    process.exit(1);
  }

  console.log('✅ Connected to Supabase');
  return tables;
}

async function exportSchemaViaCLI() {
  /**
   * Use Supabase CLI to export schema (more reliable)
   * Requires: supabase-cli installed and logged in
   */
  try {
    console.log('\n📡 Exporting schema via Supabase CLI...');

    const projectRef = SUPABASE_URL.split('.')[0].replace('https://', '');
    console.log(`   Project: ${projectRef}`);

    // Export schema
    const { stdout, stderr } = await execAsync(
      `supabase db pull --project-ref=${projectRef}`,
      { cwd: process.cwd() }
    );

    if (stderr && !stderr.includes('warning')) {
      console.error('⚠️  CLI stderr:', stderr);
    }

    console.log('✅ Schema exported via CLI');
    return true;
  } catch (error) {
    console.log('⚠️  CLI export failed (this is OK), will use API fallback');
    return false;
  }
}

async function generateMigrationFile(schema) {
  /**
   * Generate migration file from schema dump
   * This is a comprehensive snapshot for replication
   */
  const timestamp = new Date().toISOString().replace(/[-T:.Z]/g, '').slice(0, 12);
  const migrationNumber = String(timestamp).padStart(4, '0');

  const filename = `supabase/migrations/${migrationNumber}_schema-snapshot.sql`;
  const migrationPath = resolve(process.cwd(), filename);

  // Ensure directory exists
  const dirPath = resolve(process.cwd(), 'supabase/migrations');
  if (!existsSync(dirPath)) {
    mkdirSync(dirPath, { recursive: true });
  }

  const migration = `-- ═══════════════════════════════════════════════════════════════════
-- Schema Snapshot: ${new Date().toISOString().split('T')[0]}
-- Generated by: scripts/export-schema.mjs
--
-- This file captures the complete current schema from Supabase.
-- Use this to:
-- 1. Replicate schema in new Supabase project
-- 2. Document schema state
-- 3. Set up local PostgreSQL with same structure
-- ═══════════════════════════════════════════════════════════════════

-- TODO: Paste actual schema export here
-- Run: supabase db pull
-- Then copy output from supabase/migrations/ here
`;

  writeFileSync(migrationPath, migration, 'utf8');
  console.log(`\n✅ Migration template created: ${filename}`);
  return filename;
}

async function main() {
  console.log('╔══════════════════════════════════════════════════════╗');
  console.log('║  AURA MARKETPLACE — Schema Export Tool               ║');
  console.log('║  Export current Supabase schema for replication      ║');
  console.log('╚══════════════════════════════════════════════════════╝');

  try {
    // Try CLI first (more reliable)
    const cliSuccess = await exportSchemaViaCLI();

    if (!cliSuccess) {
      console.log('\n📝 Manual export needed:');
      console.log('   1. Install Supabase CLI: npm install -g supabase');
      console.log('   2. Login: supabase login');
      console.log('   3. Link project: supabase link --project-ref=YOUR_PROJECT_REF');
      console.log('   4. Pull schema: supabase db pull');
      console.log('   5. Schema will be in: supabase/migrations/');
      process.exit(0);
    }

    console.log('\n✅ Schema export complete!');
    console.log('\n📝 Next steps:');
    console.log('   1. Review supabase/migrations/');
    console.log('   2. Run migrations in target Supabase project');
    console.log('   3. Run: node scripts/seed.mjs (to populate data)');

  } catch (error) {
    console.error('❌ Export failed:', error.message);
    process.exit(1);
  }
}

main();
